name: Test Changes in a Matrix

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.packages.outputs.changes}}
    steps:
      - name: Detect Changed Packages
        uses: dorny/paths-filter@v2
        id: packages
        with:
          list-files: "shell"
          filters: |
            apples:
              - 'apples/**'
            oranges:
              - 'oranges/**'
    
  test_apples:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix: [apples, oranges]
    steps:
