name: ${{ github.ref}}
on: push

jobs:
  # changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     packages: ${{ steps.packages.outputs.changes }}
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #     - name: Detect Changed Packages
  #       uses: dorny/paths-filter@v2
  #       id: packages
  #       with:
  #         list-files: "shell"
  #         filters: |
  #           apples:
  #             - 'apples/**'
  #           oranges:
  #             - 'oranges/**'
    
  # test_apples:
  #   runs-on: ubuntu-latest
  #   needs: changes
  #   strategy:
  #     matrix:
  #       app: ${{ fromJSON(needs.changes.outputs.packages) }}
  #   steps:
  #     - name: Check Postive Changes
  #       run: echo "${{ matrix.app }} Changed"


  test_env:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment
        uses: actions/checkout@v2
        with:
          fetch-depth: 0        
      - run: |
          VAR1=$(git rev-parse ${{ github.ref }}^)
          VAR2=${GITHUB_REF}^
          echo "VAR1: ${VAR1}"
          echo "VAR2: ${VAR2}"

