name: Test Changes in a Matrix

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.packages.outputs.changes}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Detect Changed Packages
        uses: dorny/paths-filter@v2
        id: packages
        with:
          list-files: "shell"
          filters: |
            apples:
              - 'apples/**'
            oranges:
              - 'oranges/**'
    
  test_apples:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        apps: [apples, oranges]
    steps:
      - name: Check Apple Changes
        if: contains(${{ needs.changes.outputs.packages }}, ${{ matrix.apps }})
        run: |
          echo "App ${{ matrix.apps }} had a change"
          echo ${{ needs.changes.outputs.packages }}
          echo ${{ join(fromJSON(needs.changes.outputs.packages), ' ') }} > changed_files.txt
          if grep -q ${{ matrix.apps }} changed_files.txt; then
            echo "App ${{ matrix.apps }} had a change"
          else
            echo "App ${{ matrix.apps }} had no change"
          fi
