name: Test Changes in a Matrix

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.packages.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Detect Changed Packages
        uses: dorny/paths-filter@v2
        id: packages
        with:
          list-files: "shell"
          filters: |
            apples:
              - 'apples/**'
            oranges:
              - 'oranges/**'
    
  test_apples:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        app: ${{ needs.changes.outputs.packages }}
    steps:
      - name: Check Postive Changes
        run: echo "${{ matrix.app }} Changed"
      
