name: Test Changes in a Matrix

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    # outputs:
      # packages: ${{ steps.packages.outputs.changes }}
    steps:
        - name: check docker
          run: docker inspect rsdfs
        - name: another step
          run: docker run hello-world
        
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #     - name: Detect Changed Packages
  #       uses: dorny/paths-filter@v2
  #       id: packages
  #       with:
  #         list-files: "shell"
  #         filters: |
  #           apples:
  #             - 'apples/**'
  #           oranges:
  #             - 'oranges/**'
  #           oranges-two:
  #             - 'oranges-two/**'
    
  # test_apples:
  #   runs-on: ubuntu-latest
  #   needs: changes
  #   if: ${{ contains(needs.changes.outputs.packages, 'apples') }}
  #   steps:
  #     - name: Check Postive Changes
  #       run: echo "apples Changed"
  
  # test_oranges:
  #   runs-on: ubuntu-latest
  #   needs: changes
  #   if: ${{ contains(fromJSON(needs.changes.outputs.packages), 'oranges') }}
  #   steps:
  #     - name: Check Negative Changes
  #       run: echo "oranges Changed"

  # test_oranges_two:
  #   runs-on: ubuntu-latest
  #   needs: changes
  #   if: ${{ contains(fromJSON(needs.changes.outputs.packages), 'oranges-two') }}
  #   steps:
  #     - name: Check Oranges-Two Changes
  #       run: echo "oranges-two Changed"
